# Generated by Django 5.1.3 on 2025-10-30 05:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year_series", models.CharField(max_length=20)),
                ("period", models.CharField(max_length=200)),
                ("status", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CorrectAndWrongCountsPerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.IntegerField(blank=True, null=True)),
                ("number", models.IntegerField()),
                (
                    "question_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("correct_counts", models.IntegerField()),
                ("wrong_counts", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HighPQuestionsReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.IntegerField(blank=True, null=True)),
                ("high_p_q", models.CharField(blank=True, max_length=200, null=True)),
                ("number", models.IntegerField()),
                ("percentage", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="LowPQuestionsReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.IntegerField(blank=True, null=True)),
                ("low_p_q", models.CharField(blank=True, max_length=200, null=True)),
                ("number", models.IntegerField()),
                ("percentage", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PercentageWeightPerAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "percentage_w_assess",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("assessment_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PercentageWeightPerTos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pwd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("row_id", models.IntegerField(blank=True, null=True)),
                ("group_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.IntegerField(blank=True, null=True)),
                ("percentage_weight", models.IntegerField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
                ("topic", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentsTop5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.IntegerField(blank=True, null=True)),
                ("first_name", models.CharField(blank=True, max_length=200, null=True)),
                ("lastname", models.CharField(blank=True, max_length=200, null=True)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("rank", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_name", models.CharField(max_length=50)),
                ("subject_code", models.CharField(max_length=10, null=True)),
                ("subject_pw", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subtopic_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TableRestrictCountsPerCategoryReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.IntegerField(blank=True, null=True)),
                ("remembering", models.IntegerField()),
                ("creating", models.IntegerField()),
                ("understanding", models.IntegerField()),
                ("applying", models.IntegerField()),
                ("analyzing", models.IntegerField()),
                ("evaluating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "assessment_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "remembering",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "understanding",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "applying",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "analyzing",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "evaluating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "creating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subject",
                    ),
                ),
                (
                    "competencies",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subtopic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentRecordsDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "subject_code",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("assessment_id", models.IntegerField(blank=True, null=True)),
                ("remembering", models.IntegerField()),
                ("creating", models.IntegerField()),
                ("understanding", models.IntegerField()),
                ("applying", models.IntegerField()),
                ("analyzing", models.IntegerField()),
                ("evaluating", models.IntegerField()),
                ("category_total", models.IntegerField(blank=True, null=True)),
                (
                    "remembering_correct_total",
                    models.IntegerField(blank=True, null=True),
                ),
                ("creating_correct_total", models.IntegerField(blank=True, null=True)),
                (
                    "understanding_correct_total",
                    models.IntegerField(blank=True, null=True),
                ),
                ("applying_correct_total", models.IntegerField(blank=True, null=True)),
                ("analyzing_correct_total", models.IntegerField(blank=True, null=True)),
                (
                    "evaluating_correct_total",
                    models.IntegerField(blank=True, null=True),
                ),
                ("category_correct_total", models.IntegerField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoriesCountPercentage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remembering", models.IntegerField()),
                ("creating", models.IntegerField()),
                ("understanding", models.IntegerField()),
                ("applying", models.IntegerField()),
                ("analyzing", models.IntegerField()),
                ("evaluating", models.IntegerField()),
                (
                    "remembering_correct_total",
                    models.IntegerField(blank=True, null=True),
                ),
                ("creating_correct_total", models.IntegerField(blank=True, null=True)),
                (
                    "understanding_correct_total",
                    models.IntegerField(blank=True, null=True),
                ),
                ("applying_correct_total", models.IntegerField(blank=True, null=True)),
                ("analyzing_correct_total", models.IntegerField(blank=True, null=True)),
                (
                    "evaluating_correct_total",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=600)),
                ("correct_answer", models.CharField(max_length=200)),
                ("distructor1", models.CharField(max_length=200)),
                ("distructor2", models.CharField(max_length=200)),
                ("distructor3", models.CharField(max_length=200)),
                ("status", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.category",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subject",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subtopic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerKeyTableOfSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                ("number", models.IntegerField(blank=True, null=True)),
                ("row_id", models.IntegerField(blank=True, null=True)),
                ("tos_exam_id", models.IntegerField(blank=True, null=True)),
                ("a", models.CharField(blank=True, max_length=300, null=True)),
                ("b", models.CharField(blank=True, max_length=300, null=True)),
                ("c", models.CharField(blank=True, max_length=300, null=True)),
                ("d", models.CharField(blank=True, max_length=300, null=True)),
                ("correct_choice", models.CharField(max_length=1)),
                ("correct_answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.IntegerField(default=0)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.questionnaire",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subject",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subtopic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerKeyAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                ("assessment_exam_id", models.IntegerField(blank=True, null=True)),
                ("a", models.CharField(blank=True, max_length=300, null=True)),
                ("b", models.CharField(blank=True, max_length=300, null=True)),
                ("c", models.CharField(blank=True, max_length=300, null=True)),
                ("d", models.CharField(blank=True, max_length=300, null=True)),
                ("number", models.IntegerField(blank=True, null=True)),
                ("correct_choice", models.CharField(max_length=1)),
                ("correct_answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.IntegerField(default=0)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.assessment",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.questionnaire",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "studentschoolid",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("lastname", models.CharField(max_length=200)),
                ("firstname", models.CharField(max_length=200)),
                ("studentid", models.IntegerField(unique=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentsScoreAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(blank=True, null=True)),
                ("exam_id", models.IntegerField(blank=True, null=True)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("lastname", models.CharField(blank=True, max_length=200, null=True)),
                ("firstname", models.CharField(blank=True, max_length=200, null=True)),
                ("studentid", models.IntegerField(blank=True, null=True)),
                ("period", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.answerkeyassessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentsScoreTos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(blank=True, null=True)),
                ("exam_id", models.IntegerField(blank=True, null=True)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("lastname", models.CharField(blank=True, max_length=200, null=True)),
                ("firstname", models.CharField(blank=True, max_length=200, null=True)),
                ("studentid", models.IntegerField(blank=True, null=True)),
                ("period", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.answerkeytableofspecification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentStatsAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_id", models.IntegerField(blank=True, null=True)),
                ("total_questions_taken", models.IntegerField()),
                ("total_questions_score", models.IntegerField()),
                ("assessment_taken_count", models.IntegerField(blank=True, null=True)),
                ("curr_assess_percentage", models.IntegerField(blank=True, null=True)),
                ("final_assess_percentage", models.FloatField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectCountPercentage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_q_counts_per_subject", models.IntegerField()),
                ("total_correct_counts_per_subject", models.IntegerField()),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentStatsTos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastname", models.CharField(blank=True, max_length=200, null=True)),
                ("firstname", models.CharField(blank=True, max_length=200, null=True)),
                ("question_count", models.IntegerField(default=0)),
                ("correct_count", models.IntegerField(default=0)),
                ("row_id", models.IntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.students",
                    ),
                ),
                (
                    "tos_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.answerkeytableofspecification",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subtopic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableOfSpecification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("group_id", models.IntegerField(db_index=True)),
                ("row_id", models.IntegerField(blank=True, null=True)),
                (
                    "pwd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "understanding",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "remembering",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "analyzing",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "creating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "evaluating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "applying",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.academicyear",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subject",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subtopic",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answerkeytableofspecification",
            name="tableofspecification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="criminology.tableofspecification",
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("topic_name", models.CharField(max_length=200)),
                (
                    "subject_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criminology.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tableofspecification",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="criminology.topic",
            ),
        ),
        migrations.AddField(
            model_name="subtopic",
            name="topic_subtopic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="criminology.topic"
            ),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="criminology.topic",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="criminology.topic",
            ),
        ),
        migrations.AddField(
            model_name="answerkeytableofspecification",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="criminology.topic",
            ),
        ),
    ]